-- 알림 배치 앱 소유 스키마 (batch-design §6). 본 앱이 소유하는 테이블만 관리한다.
-- 공유 DB의 외부 소유 테이블(tb_notification, tb_photo_image)은 외부가 소유하며 읽기 전용으로 사용하므로
-- 본 마이그레이션 대상이 아니다. (Flyway baseline-on-migrate=true 로 기존 외부 테이블과 공존)

-- 발송 이력 (NotificationLogEntity). 중복 방지: UNIQUE(user_id, notification_type, business_date).
CREATE TABLE notification_log (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    notification_type VARCHAR(32)  NOT NULL,
    message_tone      VARCHAR(16)  NOT NULL,
    variable_applied  BOOLEAN      NOT NULL,
    title             VARCHAR(255) NOT NULL,
    body              VARCHAR(500) NOT NULL,
    business_date     DATE         NOT NULL,
    fcm_result        VARCHAR(16)  NOT NULL,
    sent_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_notification_log_user_type_date UNIQUE (user_id, notification_type, business_date)
);

CREATE INDEX ix_notification_log_business_date ON notification_log (business_date);

-- 공휴일 (HolidayEntity). 본 앱 소유, 수동 시드.
CREATE TABLE holiday (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    holiday_date       DATE        NOT NULL,
    name               VARCHAR(64) NOT NULL,
    notify_offset_days INTEGER     NOT NULL,
    CONSTRAINT uq_holiday_date UNIQUE (holiday_date)
);
